### ISSUE TITLE
recyclerView couldn't retain it's position after orientation change

### ISSUE THREAD

**Issue by sdzshn3** [sdzshn3/News24-7-RV#1]
If we scroll down through the articles and then we change the orientation of the screen, then app couldn't retain where it was at. It just scrolls to top again.

Steps to reproduce issue:
Open app > select language > in any of the news category, scroll down through the list > change orientation / rotate your phone.
Now you can see list is scrolled to top automatically which shouldn't happen.

**Comment by Abhinavlamba** [comment]
Assign this issue to me.

**Comment by Abhinavlamba** [comment]
I would like to work on this issue.

**Comment by sdzshn3** [comment]
Thanks Abhinav. Proceed.

**Comment by Abhinavlamba** [comment]
Task completed :)

**Comment by sdzshn3** [comment]
Thanks. It's solved
