### ISSUE TITLE
Is separate ViewModels and Repository necessary?

### ISSUE THREAD

**Issue by sdzshn3** [sdzshn3/News24-7-RV#12]
You can see that each each news category has one separate ViewModel class and repository class.

If you think we can club all the ViewModel classes in a single ViewModel class and similarly, all repositories in a single repository class, then club them.

What do you say guys?

**Comment by codersanjeev** [comment]
It is necessary to keep ViewModel and Repository separate.
I need them to be separate for this issue #5 
![arch](https://user-images.githubusercontent.com/34043056/50348483-e21b1080-055e-11e9-88f5-0c98279b7725.png)

**Comment by sdzshn3** [comment]
Sorry if my explanation was wrong.
But I'm saying that clubbing all view model classes in a single class and also, clubbing all repositories in a single repository. But not repository and ViewModel class together..

**Comment by codersanjeev** [comment]
Okay, got it... I should have read it carefully. 
I will see if they can be merged into one or not :+1:

**Comment by amy6** [comment]
I think we should do this. There should be a single Repository and ViewModel class as base classes and we can extend those classes to implement specific functionality as required. Same goes for the fragment classes too. From what I can see all fragment classes define the same set of methods. If we create a base Fragment class with all the common functionality, inject the required dependencies and extend them for specific requirements, it will reduce a lot of code. 
If we continue with the existing pattern and if there are more categories of news to be added in the future, it simply leads to more redundant code. Any new change for any fragment needs to be duplicated for all fragments, repositories and view models. This is one of the reasons I have been procrastinating on issue #3 It requires me to make the same change everywhere and it does not feel good.

So @sdzshn3 I'd like to work on modularizing the code first and then work on other issues. Let me know your thoughts.

**Comment by sdzshn3** [comment]
Ok. Thats great @amy6 Please carry-on.
Just few points to mention,
After combining them as you said, I want the functionality like,
First user opens app. Now app opens top headlines.
And then user clicks on science news then if user clicks again on top headlines, app should not get the data again from API. Instead, it should load the existing data available. (This is what current app does). On pull down to refresh, it should get data from API. 

And there's a waiting PR for this project. Please check it and let me know if it stops you to go further.
If it doesn't, I'll accept the PR.

**Comment by amy6** [comment]
Sounds good. I'll make sure the existing functionality isn't broken. I'll be working on this change starting tomorrow. So please go ahead with merging the existing PR.
