### ISSUE TITLE
Include room Database and implement offline feature

### ISSUE THREAD

**Issue by sdzshn3** [sdzshn3/News24-7-RV#5]
When the app launches for first time, get the news info and show it to user and also save it to DB.
Or first save news info to DB and after completion, show to user by taking data from DB.

When the user launches app next time (not first time) if internet connection is active, then remove old data and save new data to DB & show to user.

If the internet connection is not active, check if data is available in DB or not. If available, show it to user and let the user know that, the content is old and offline.

**Comment by codersanjeev** [comment]
I am working on this.

**Comment by sdzshn3** [comment]
Cool...😃 Assigned it to you. Use Room DB to save the articles. You are free to do as much as you like. If you have any more ideas for app, create a new issue and implement it.
