### ISSUE TITLE
Add bottom margin to the last list item.

### ISSUE THREAD

**Issue by sdzshn3** [sdzshn3/News24-7-RV#6]
The last article is getting covered under the ad.
So, we need to add bottom margin to the last list item so that it will not be covered under ad.

**Comment by Abhinavlamba** [comment]
I would like to solve this issue.

**Comment by sdzshn3** [comment]
I have assigned it to you.
Please proceed.

**Comment by Abhinavlamba** [comment]
Thank you!

**Comment by sdzshn3** [comment]
Thanks guys. It's solved.
