### ISSUE TITLE
Add repository class for all AndroidViewModel classes

### ISSUE THREAD

**Issue by sdzshn3** [sdzshn3/News24-7-RV#7]
There should be a mediater repository class between Android ViewModel class and retrofit callback.
Here's what you need to do,
Create new repository for each ViewModel class.
Place the retrofit callback inside repository class, also, save the List data into a LiveData variable, add a getter method to get data.

Then in ViewModel class get data from the repository class instead of from retrofit callback.

**Comment by codersanjeev** [comment]
I would like to work on this issue.

**Comment by sdzshn3** [comment]
Thanks for the help.
You can take this project as a reference: https://github.com/sdzshn3/Notes_LD-VM-RoomDB

**Comment by sdzshn3** [comment]
Hey Sanjeev, could you please run the app and scroll down a bit and change the screen orientation and check if it scrolls automatically to top or it could able to persist its position?

**Comment by codersanjeev** [comment]
I have checked, it scrolls automatically to the top when the screen orientation is changed @sdzshn3

**Comment by sdzshn3** [comment]
Ohh..😯
It's ok. I'll look into that. Thanks for adding repository classes.
