### ISSUE TITLE
Instructions for how to setup the project

### ISSUE THREAD

**Issue by codersanjeev** [sdzshn3/News24-7-RV#8]
Add the instructions on how to build and run this project in Android Studio in README file.
Particularly, the instructions about the google-services.json file which needs to be added to successfully build and run the project.

**Comment by sdzshn3** [comment]
I'm sorry about that. I'll add ASAP

**Comment by sdzshn3** [comment]
Added. Thanks
Incase if i push latest code, I'll make sure to do those changes so that you can build it without any hassles.
